# Form implementation generated from reading ui file './qt_gui/QtProject/MCI_Planning_Tool_v4.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import os
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QFileDialog, QMainWindow
from pyrecodes_hospitals import main
from pyrecodes_hospitals import ResilienceCalculator
from pyrecodes_hospitals import Plotter
from pyrecodes_hospitals import ReportGenerator
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import random

random.seed(1)

# Add the parent directory to the Python path
parent_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(parent_dir)

# ADDITIONAL_DATA_LOCATION = os.path.abspath(os.path.dirname(__file__)) + '/' # for packaging on MAC
# ADDITIONAL_DATA_LOCATION = os.path.abspath(os.path.dirname(__file__)) + '\\' # for packaging on WIN
ADDITIONAL_DATA_LOCATION = './additional_data/' # for running from source

PREDEFINED_SCENARIOS_JSON_FILE=ADDITIONAL_DATA_LOCATION + 'Hospital_Pre-Defined_StressScenarios.json'

RESOURCE_UNITS = {'Nurse': '[Nurse/hour]',
                  'Fuel': '[L/hour]',
                  'Water': '[L/hour]',
                  'Oxygen': '[L/hour]',
                  'MedicalDrugs': '[1 - available, 0 - not available]',
                  'Blood': '[Blood bag]',
                  'Stretcher': '[Stretcher]',
                  'MCI_Kit_Walking_EmergencyDepartment': '[Patients Treated]',
                  'MCI_Kit_NonWalking_EmergencyDepartment': '[Patients Treated]',
                  'MCI_Kit_NonWalking_OperatingTheater': '[Patients Treated]',
                  'MCI_Kit_NonWalking_HighDependencyUnit': '[Patients Treated]',
                  'MCI_Kit_NonWalking_Medical/SurgicalDepartment': '[Patients Treated]',
                  'EmergencyDepartment_Bed': '[Bed]',
                  'OperatingTheater_Bed': '[Bed]',
                  'Medical/SurgicalDepartment_Bed': '[Bed]',
                  'HighDependencyUnit_Bed': '[Bed]',
                  'RestOfHospital_Bed': '[Bed]'}

DEPARTMENTS = ['All', 'Emergency Department', 'Operating Theater', 'High Dependency Unit', 'Medical/Surgical Department', 'Rest Of Hospital']

def get_resilience_calculator(system, department, patient_type, resilience_calculator_class=ResilienceCalculator.HospitalMeasureOfServiceCalculator):
    for resilience_calculator in system.resilience_calculators:
        if isinstance(resilience_calculator, resilience_calculator_class):
            if resilience_calculator.scope == [department]:
                if resilience_calculator_class == ResilienceCalculator.HospitalMeasureOfServiceCalculator or resilience_calculator_class == ResilienceCalculator.CauseOfDeathCalculator:
                    if resilience_calculator.resources == [patient_type]:
                        return resilience_calculator
                else:
                    return resilience_calculator


class Ui_MainWindow(object):

    def selectFile(self):
        self.label_input_file_location.setText(QFileDialog.getOpenFileName()[0])

    def run_assessment(self):
        self.progressBar.setProperty("value", 0)
        MCI_scenario_parameters = self.get_MCI_scenario_parameters()
        self.input_file_location = self.label_input_file_location.text()
        system = main.run_from_gui(self.input_file_location, MCI_scenario_parameters, ADDITIONAL_DATA_LOCATION, self.progressBar, self.app) 
        system.calculate_resilience()
        self.system = system
        self.change_resource_labels_color() 
        self.update_patient_type_dropdown()
        self.update_measures_of_service()  
        self.comboBox_department.currentIndexChanged.connect(lambda: self.update_measures_of_service())
        self.comboBox_patient_type.currentIndexChanged.connect(lambda: self.update_measures_of_service())    
        self.second_windows = []         
        self.app.processEvents()

    def get_MCI_scenario_parameters(self):
        if self.radioButton_preDefinedMCI.isChecked():            
            MCI_type = self.comboBox_preDefinedMCIType.currentText()
            number_of_patients = int(self.textEdit_NumberOfPatients.toPlainText())
            investigated_period = int(self.textEdit_InvestigatedPeriod.toPlainText())
            predefined_stress_scenarios = main.read_file(PREDEFINED_SCENARIOS_JSON_FILE)
            patient_arrival = predefined_stress_scenarios[MCI_type]
            return {"MCI_type": MCI_type, "number_of_patients": number_of_patients, "investigated_period": investigated_period, "patient_arrival": patient_arrival}
        elif self.radioButton_userDefinedMCI.isChecked():
            return {}

    def show_plot(self, resource_name):
        self.second_windows.append(SecondWindow(self.system, resource_name, self.comboBox_department, self.comboBox_patient_type))
        self.second_windows[-1].setWindowTitle(resource_name)
        self.second_windows[-1].resize(500, 500)
        self.second_windows[-1].show()

    def change_resource_labels_color(self):
        map_resources_to_labels = {'Nurse': self.label_nurses, 
                                   'Fuel': self.label_fuel, 
                                   'Water': self.label_water, 
                                   'Oxygen': self.label_oxygen, 
                                   'MedicalDrugs': self.label_medical_drugs,
                                   'Blood': self.label_blood,
                                   'Stretcher': self.label_stretchers,
                                   'MCI_Kit_NonWalking_EmergencyDepartment': self.label_MCI_kits, 
                                   'MCI_Kit_NonWalking_OperatingTheater': self.label_MCI_kits, 
                                   'MCI_Kit_NonWalking_HighDependencyUnit': self.label_MCI_kits, 
                                   'MCI_Kit_NonWalking_Medical/SurgicalDepartment': self.label_MCI_kits, 
                                   'MCI_Kit_Walking_EmergencyDepartment': self.label_MCI_kits, 
                                   'EmergencyDepartment_Bed': self.label_beds, 
                                   'OperatingTheater_Bed': self.label_beds,
                                   'Medical/SurgicalDepartment_Bed': self.label_beds,
                                   'HighDependencyUnit_Bed': self.label_beds,
                                   'RestOfHospital_Bed': self.label_beds
                                   }
        
        recodes_calculator = self.system.resilience_calculators[0]
        # first set all labels to green
        for label in map_resources_to_labels.values():
            label.setStyleSheet("color: green;")
        # now set labels to red if there is unmet demand
        for resource_name in recodes_calculator.lack_of_resilience.keys():
            if resource_name in map_resources_to_labels.keys() and recodes_calculator.lack_of_resilience[resource_name] > 0:
                map_resources_to_labels[resource_name].setStyleSheet("color: red;" )
    
    def change_measures_of_service_labels(self):
        self.label_mortality_rate_before_24h_output.setText(str(round(self.measures_of_service['MortalityRateBefore24H']*100, 2)) + '%')
        self.label_mortality_rate_after_24h_output.setText(str(round(self.measures_of_service['MortalityRateAfter24H']*100, 2)) + '%')
        self.label_average_length_of_stay_output.setText(str(int(self.measures_of_service['AverageLengthOfStay'])) + 'h')
        self.label_surgeries_performed_output.setText(str(int(self.measures_of_service['SurgeriesPerformed'])))
        self.label_surgeries_cancelled_output.setText(str(int(self.measures_of_service['SurgeriesCancelled'])))   

    def update_patient_type_dropdown(self):
        if self.comboBox_patient_type.count() == 0:        
            self.comboBox_patient_type.addItems(self.get_patient_types(self.system))
            self.comboBox_patient_type.setCurrentIndex(0)
    
    def update_MCI_stress_scenario_dropdown(self):
        predefined_stress_scenarios = main.read_file(PREDEFINED_SCENARIOS_JSON_FILE)
        stress_scenario_names = list(predefined_stress_scenarios.keys())
        self.comboBox_preDefinedMCIType.addItems(stress_scenario_names)
        self.comboBox_preDefinedMCIType.setCurrentIndex(0)
    
    @staticmethod
    def get_patient_types(system):
        return ['All'] + list(system.components[0].patient_library.keys())
    
    def update_measures_of_service(self):
        department = self.comboBox_department.currentText().replace(" ","")
        patient_type = self.comboBox_patient_type.currentText()
        # QuickFix. Not pretty but works. Fix later.
        if patient_type == '':
            return
        resilience_calculator = get_resilience_calculator(self.system, department, patient_type, resilience_calculator_class=ResilienceCalculator.HospitalMeasureOfServiceCalculator)
        self.set_measures_of_service(resilience_calculator)
        self.change_measures_of_service_labels()
        self.app.processEvents()  
    
    def set_measures_of_service(self, resilience_calculator):
        self.measures_of_service = resilience_calculator.measures_of_service

    def format_MCI_kit_resource_name(self):
        department = self.comboBox_department_MCI_Kits.currentText().replace(" ","")
        GUI_string_to_resource_name = {'Walking|EmergencyDepartment': 'Walking_EmergencyDepartment',
                                       'Non-Walking|EmergencyDepartment': 'NonWalking_EmergencyDepartment',
                                       'Non-Walking|OperatingTheater': 'NonWalking_OperatingTheater',
                                       'Non-Walking|HighDependencyUnit': 'NonWalking_HighDependencyUnit',
                                       'Non-Walking|Medical/SurgicalDepartment': 'NonWalking_Medical/SurgicalDepartment'
                                       }
        return f'MCI_Kit_{GUI_string_to_resource_name[department]}'
    
    def format_bed_resource_name(self):
        department = self.comboBox_department_Beds.currentText().replace(" ","")
        return f'{department}_Bed'
    
    def disableMCIScenarioInputForCustomScenario(self, checked):
        self.comboBox_preDefinedMCIType.setEnabled(not checked)
        self.textEdit_NumberOfPatients.setEnabled(not checked)
        self.textEdit_InvestigatedPeriod.setEnabled(not checked)

    def setupUi(self, MainWindow, app=None):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 698)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_select_file = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_select_file.sizePolicy().hasHeightForWidth())
        self.button_select_file.setSizePolicy(sizePolicy)
        self.button_select_file.setMinimumSize(QtCore.QSize(150, 32))
        self.button_select_file.setMaximumSize(QtCore.QSize(150, 32))
        self.button_select_file.setObjectName("button_select_file")
        self.horizontalLayout.addWidget(self.button_select_file)
        self.label_input_file_location = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_input_file_location.setObjectName("label_input_file_location")
        self.horizontalLayout.addWidget(self.label_input_file_location, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 781, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_MassCasualtyIncidentScenario = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_MassCasualtyIncidentScenario.setFont(font)
        self.label_MassCasualtyIncidentScenario.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_MassCasualtyIncidentScenario.setObjectName("label_MassCasualtyIncidentScenario")
        self.verticalLayout_8.addWidget(self.label_MassCasualtyIncidentScenario)
        self.radioButton_userDefinedMCI = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_userDefinedMCI.sizePolicy().hasHeightForWidth())
        self.radioButton_userDefinedMCI.setSizePolicy(sizePolicy)
        self.radioButton_userDefinedMCI.setObjectName("radioButton_userDefinedMCI")
        self.verticalLayout_8.addWidget(self.radioButton_userDefinedMCI)
        self.radioButton_preDefinedMCI = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_preDefinedMCI.sizePolicy().hasHeightForWidth())
        self.radioButton_preDefinedMCI.setSizePolicy(sizePolicy)
        self.radioButton_preDefinedMCI.setObjectName("radioButton_preDefinedMCI")
        self.verticalLayout_8.addWidget(self.radioButton_preDefinedMCI)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_preDefinedMCIType = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_preDefinedMCIType.sizePolicy().hasHeightForWidth())
        self.label_preDefinedMCIType.setSizePolicy(sizePolicy)
        self.label_preDefinedMCIType.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_preDefinedMCIType.setObjectName("label_preDefinedMCIType")
        self.horizontalLayout_3.addWidget(self.label_preDefinedMCIType)
        self.comboBox_preDefinedMCIType = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_preDefinedMCIType.sizePolicy().hasHeightForWidth())
        self.comboBox_preDefinedMCIType.setSizePolicy(sizePolicy)
        self.comboBox_preDefinedMCIType.setMinimumSize(QtCore.QSize(200, 32))
        self.comboBox_preDefinedMCIType.setMaximumSize(QtCore.QSize(1000, 32))
        self.comboBox_preDefinedMCIType.setObjectName("comboBox_preDefinedMCIType")
        self.horizontalLayout_3.addWidget(self.comboBox_preDefinedMCIType)
        self.label_NumberOfPatients = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_NumberOfPatients.sizePolicy().hasHeightForWidth())
        self.label_NumberOfPatients.setSizePolicy(sizePolicy)
        self.label_NumberOfPatients.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_NumberOfPatients.setObjectName("label_NumberOfPatients")
        self.horizontalLayout_3.addWidget(self.label_NumberOfPatients)
        self.textEdit_NumberOfPatients = QtWidgets.QTextEdit(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_NumberOfPatients.sizePolicy().hasHeightForWidth())
        self.textEdit_NumberOfPatients.setSizePolicy(sizePolicy)
        self.textEdit_NumberOfPatients.setMinimumSize(QtCore.QSize(100, 25))
        self.textEdit_NumberOfPatients.setMaximumSize(QtCore.QSize(300, 25))
        self.textEdit_NumberOfPatients.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textEdit_NumberOfPatients.setObjectName("textEdit_NumberOfPatients")
        self.horizontalLayout_3.addWidget(self.textEdit_NumberOfPatients)
        self.label_InvestigatedPeriod = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_InvestigatedPeriod.sizePolicy().hasHeightForWidth())
        self.label_InvestigatedPeriod.setSizePolicy(sizePolicy)
        self.label_InvestigatedPeriod.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_InvestigatedPeriod.setObjectName("label_InvestigatedPeriod")
        self.horizontalLayout_3.addWidget(self.label_InvestigatedPeriod)
        self.textEdit_InvestigatedPeriod = QtWidgets.QTextEdit(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_InvestigatedPeriod.sizePolicy().hasHeightForWidth())
        self.textEdit_InvestigatedPeriod.setSizePolicy(sizePolicy)
        self.textEdit_InvestigatedPeriod.setMinimumSize(QtCore.QSize(100, 25))
        self.textEdit_InvestigatedPeriod.setMaximumSize(QtCore.QSize(300, 25))
        self.textEdit_InvestigatedPeriod.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.textEdit_InvestigatedPeriod.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textEdit_InvestigatedPeriod.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.textEdit_InvestigatedPeriod.setObjectName("textEdit_InvestigatedPeriod")
        self.horizontalLayout_3.addWidget(self.textEdit_InvestigatedPeriod)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 180, 781, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button_run = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.button_run.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_run.sizePolicy().hasHeightForWidth())
        self.button_run.setSizePolicy(sizePolicy)
        self.button_run.setMaximumSize(QtCore.QSize(150, 16777215))
        self.button_run.setObjectName("button_run")
        self.horizontalLayout_5.addWidget(self.button_run)
        self.progressBar = QtWidgets.QProgressBar(parent=self.horizontalLayoutWidget_3)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_5.addWidget(self.progressBar)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 230, 781, 412))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_measures_of_service = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_measures_of_service.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_measures_of_service.setFont(font)
        self.label_measures_of_service.setObjectName("label_measures_of_service")
        self.verticalLayout_9.addWidget(self.label_measures_of_service)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_choose_department = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_choose_department.sizePolicy().hasHeightForWidth())
        self.label_choose_department.setSizePolicy(sizePolicy)
        self.label_choose_department.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_choose_department.setObjectName("label_choose_department")
        self.verticalLayout_11.addWidget(self.label_choose_department)
        self.comboBox_department = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_department.sizePolicy().hasHeightForWidth())
        self.comboBox_department.setSizePolicy(sizePolicy)
        self.comboBox_department.setMinimumSize(QtCore.QSize(250, 32))
        self.comboBox_department.setMaximumSize(QtCore.QSize(500, 32))
        self.comboBox_department.setObjectName("comboBox_department")
        self.verticalLayout_11.addWidget(self.comboBox_department)
        self.label_choose_patient_type = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_choose_patient_type.sizePolicy().hasHeightForWidth())
        self.label_choose_patient_type.setSizePolicy(sizePolicy)
        self.label_choose_patient_type.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_choose_patient_type.setObjectName("label_choose_patient_type")
        self.verticalLayout_11.addWidget(self.label_choose_patient_type)
        self.comboBox_patient_type = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_patient_type.sizePolicy().hasHeightForWidth())
        self.comboBox_patient_type.setSizePolicy(sizePolicy)
        self.comboBox_patient_type.setMinimumSize(QtCore.QSize(250, 32))
        self.comboBox_patient_type.setMaximumSize(QtCore.QSize(500, 32))
        self.comboBox_patient_type.setObjectName("comboBox_patient_type")
        self.verticalLayout_11.addWidget(self.comboBox_patient_type)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_mortality_rate_before_24h_output = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mortality_rate_before_24h_output.sizePolicy().hasHeightForWidth())
        self.label_mortality_rate_before_24h_output.setSizePolicy(sizePolicy)
        self.label_mortality_rate_before_24h_output.setMaximumSize(QtCore.QSize(50, 25))
        self.label_mortality_rate_before_24h_output.setObjectName("label_mortality_rate_before_24h_output")
        self.gridLayout_2.addWidget(self.label_mortality_rate_before_24h_output, 0, 1, 1, 1)
        self.label_mortality_rate_after_24 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mortality_rate_after_24.sizePolicy().hasHeightForWidth())
        self.label_mortality_rate_after_24.setSizePolicy(sizePolicy)
        self.label_mortality_rate_after_24.setMaximumSize(QtCore.QSize(200, 25))
        self.label_mortality_rate_after_24.setObjectName("label_mortality_rate_after_24")
        self.gridLayout_2.addWidget(self.label_mortality_rate_after_24, 1, 0, 1, 1)
        self.label_average_length_of_stay = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_average_length_of_stay.sizePolicy().hasHeightForWidth())
        self.label_average_length_of_stay.setSizePolicy(sizePolicy)
        self.label_average_length_of_stay.setMaximumSize(QtCore.QSize(200, 25))
        self.label_average_length_of_stay.setObjectName("label_average_length_of_stay")
        self.gridLayout_2.addWidget(self.label_average_length_of_stay, 2, 0, 1, 1)
        self.label_surgeries_performed_output = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_surgeries_performed_output.sizePolicy().hasHeightForWidth())
        self.label_surgeries_performed_output.setSizePolicy(sizePolicy)
        self.label_surgeries_performed_output.setMaximumSize(QtCore.QSize(50, 25))
        self.label_surgeries_performed_output.setObjectName("label_surgeries_performed_output")
        self.gridLayout_2.addWidget(self.label_surgeries_performed_output, 3, 1, 1, 1)
        self.label_mortality_rate_before_24h = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mortality_rate_before_24h.sizePolicy().hasHeightForWidth())
        self.label_mortality_rate_before_24h.setSizePolicy(sizePolicy)
        self.label_mortality_rate_before_24h.setMaximumSize(QtCore.QSize(200, 25))
        self.label_mortality_rate_before_24h.setObjectName("label_mortality_rate_before_24h")
        self.gridLayout_2.addWidget(self.label_mortality_rate_before_24h, 0, 0, 1, 1)
        self.label_average_length_of_stay_output = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_average_length_of_stay_output.sizePolicy().hasHeightForWidth())
        self.label_average_length_of_stay_output.setSizePolicy(sizePolicy)
        self.label_average_length_of_stay_output.setMaximumSize(QtCore.QSize(50, 25))
        self.label_average_length_of_stay_output.setObjectName("label_average_length_of_stay_output")
        self.gridLayout_2.addWidget(self.label_average_length_of_stay_output, 2, 1, 1, 1)
        self.label_mortality_rate_after_24h_output = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mortality_rate_after_24h_output.sizePolicy().hasHeightForWidth())
        self.label_mortality_rate_after_24h_output.setSizePolicy(sizePolicy)
        self.label_mortality_rate_after_24h_output.setMaximumSize(QtCore.QSize(50, 25))
        self.label_mortality_rate_after_24h_output.setObjectName("label_mortality_rate_after_24h_output")
        self.gridLayout_2.addWidget(self.label_mortality_rate_after_24h_output, 1, 1, 1, 1)
        self.label_surgeries_cancelled_output = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_surgeries_cancelled_output.sizePolicy().hasHeightForWidth())
        self.label_surgeries_cancelled_output.setSizePolicy(sizePolicy)
        self.label_surgeries_cancelled_output.setMaximumSize(QtCore.QSize(50, 25))
        self.label_surgeries_cancelled_output.setObjectName("label_surgeries_cancelled_output")
        self.gridLayout_2.addWidget(self.label_surgeries_cancelled_output, 4, 1, 1, 1)
        self.label_surgeries_performed = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_surgeries_performed.sizePolicy().hasHeightForWidth())
        self.label_surgeries_performed.setSizePolicy(sizePolicy)
        self.label_surgeries_performed.setMaximumSize(QtCore.QSize(200, 25))
        self.label_surgeries_performed.setObjectName("label_surgeries_performed")
        self.gridLayout_2.addWidget(self.label_surgeries_performed, 3, 0, 1, 1)
        self.label_surgeries_cancelled = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_surgeries_cancelled.sizePolicy().hasHeightForWidth())
        self.label_surgeries_cancelled.setSizePolicy(sizePolicy)
        self.label_surgeries_cancelled.setMaximumSize(QtCore.QSize(200, 25))
        self.label_surgeries_cancelled.setObjectName("label_surgeries_cancelled")
        self.gridLayout_2.addWidget(self.label_surgeries_cancelled, 4, 0, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_medical_drugs = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_medical_drugs.setObjectName("label_medical_drugs")
        self.gridLayout.addWidget(self.label_medical_drugs, 7, 1, 1, 1)
        self.label_fuel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_fuel.setObjectName("label_fuel")
        self.gridLayout.addWidget(self.label_fuel, 4, 1, 1, 1)
        self.label_beds = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_beds.setObjectName("label_beds")
        self.gridLayout.addWidget(self.label_beds, 10, 1, 1, 1)
        self.label_water = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_water.setObjectName("label_water")
        self.gridLayout.addWidget(self.label_water, 5, 1, 1, 1)
        self.label_department_nurses = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_department_nurses.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_department_nurses.setObjectName("label_department_nurses")
        self.gridLayout.addWidget(self.label_department_nurses, 4, 2, 1, 1)
        self.label_stretchers = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_stretchers.setObjectName("label_stretchers")
        self.gridLayout.addWidget(self.label_stretchers, 9, 1, 1, 1)
        self.label_blood = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_blood.setObjectName("label_blood")
        self.gridLayout.addWidget(self.label_blood, 8, 1, 1, 1)
        self.label_resources = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_resources.setFont(font)
        self.label_resources.setObjectName("label_resources")
        self.gridLayout.addWidget(self.label_resources, 0, 1, 1, 1)
        self.label_oxygen = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_oxygen.setObjectName("label_oxygen")
        self.gridLayout.addWidget(self.label_oxygen, 6, 1, 1, 1)
        self.label_department_drugs = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_department_drugs.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_department_drugs.setObjectName("label_department_drugs")
        self.gridLayout.addWidget(self.label_department_drugs, 7, 2, 1, 1)
        self.label_MCI_kits = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_MCI_kits.setObjectName("label_MCI_kits")
        self.gridLayout.addWidget(self.label_MCI_kits, 11, 1, 1, 1)
        self.label_nurses = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_nurses.setObjectName("label_nurses")
        self.gridLayout.addWidget(self.label_nurses, 3, 1, 1, 1)
        self.label_department_fuel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_department_fuel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_department_fuel.setObjectName("label_department_fuel")
        self.gridLayout.addWidget(self.label_department_fuel, 3, 2, 1, 1)
        self.label_department_oxygen = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_department_oxygen.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_department_oxygen.setObjectName("label_department_oxygen")
        self.gridLayout.addWidget(self.label_department_oxygen, 6, 2, 1, 1)
        self.label_department_blood = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_department_blood.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_department_blood.setObjectName("label_department_blood")
        self.gridLayout.addWidget(self.label_department_blood, 8, 2, 1, 1)
        self.label_department_water = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_department_water.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_department_water.setObjectName("label_department_water")
        self.gridLayout.addWidget(self.label_department_water, 5, 2, 1, 1)
        self.label_department_stretchers = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_department_stretchers.sizePolicy().hasHeightForWidth())
        self.label_department_stretchers.setSizePolicy(sizePolicy)
        self.label_department_stretchers.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_department_stretchers.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_department_stretchers.setObjectName("label_department_stretchers")
        self.gridLayout.addWidget(self.label_department_stretchers, 9, 2, 1, 1)
        self.label_department = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_department.sizePolicy().hasHeightForWidth())
        self.label_department.setSizePolicy(sizePolicy)
        self.label_department.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_department.setFont(font)
        self.label_department.setObjectName("label_department")
        self.gridLayout.addWidget(self.label_department, 0, 2, 1, 1)
        self.comboBox_department_MCI_Kits = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_department_MCI_Kits.sizePolicy().hasHeightForWidth())
        self.comboBox_department_MCI_Kits.setSizePolicy(sizePolicy)
        self.comboBox_department_MCI_Kits.setMinimumSize(QtCore.QSize(250, 32))
        self.comboBox_department_MCI_Kits.setMaximumSize(QtCore.QSize(500, 32))
        self.comboBox_department_MCI_Kits.setObjectName("comboBox_department_MCI_Kits")
        self.gridLayout.addWidget(self.comboBox_department_MCI_Kits, 11, 2, 1, 1)
        self.comboBox_department_Beds = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_department_Beds.sizePolicy().hasHeightForWidth())
        self.comboBox_department_Beds.setSizePolicy(sizePolicy)
        self.comboBox_department_Beds.setMinimumSize(QtCore.QSize(250, 32))
        self.comboBox_department_Beds.setMaximumSize(QtCore.QSize(500, 32))
        self.comboBox_department_Beds.setObjectName("comboBox_department_Beds")
        self.gridLayout.addWidget(self.comboBox_department_Beds, 10, 2, 1, 1)
        self.button_show_plot_nurses = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_show_plot_nurses.sizePolicy().hasHeightForWidth())
        self.button_show_plot_nurses.setSizePolicy(sizePolicy)
        self.button_show_plot_nurses.setMinimumSize(QtCore.QSize(120, 32))
        self.button_show_plot_nurses.setMaximumSize(QtCore.QSize(200, 32))
        self.button_show_plot_nurses.setObjectName("button_show_plot_nurses")
        self.gridLayout.addWidget(self.button_show_plot_nurses, 3, 3, 1, 1)
        self.button_show_plot_fuel = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_show_plot_fuel.sizePolicy().hasHeightForWidth())
        self.button_show_plot_fuel.setSizePolicy(sizePolicy)
        self.button_show_plot_fuel.setMinimumSize(QtCore.QSize(120, 32))
        self.button_show_plot_fuel.setMaximumSize(QtCore.QSize(200, 32))
        self.button_show_plot_fuel.setObjectName("button_show_plot_fuel")
        self.gridLayout.addWidget(self.button_show_plot_fuel, 4, 3, 1, 1)
        self.button_show_plot_water = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_show_plot_water.sizePolicy().hasHeightForWidth())
        self.button_show_plot_water.setSizePolicy(sizePolicy)
        self.button_show_plot_water.setMinimumSize(QtCore.QSize(120, 32))
        self.button_show_plot_water.setMaximumSize(QtCore.QSize(200, 32))
        self.button_show_plot_water.setObjectName("button_show_plot_water")
        self.gridLayout.addWidget(self.button_show_plot_water, 5, 3, 1, 1)
        self.button_show_plot_oxygen = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_show_plot_oxygen.sizePolicy().hasHeightForWidth())
        self.button_show_plot_oxygen.setSizePolicy(sizePolicy)
        self.button_show_plot_oxygen.setMinimumSize(QtCore.QSize(120, 32))
        self.button_show_plot_oxygen.setMaximumSize(QtCore.QSize(200, 32))
        self.button_show_plot_oxygen.setObjectName("button_show_plot_oxygen")
        self.gridLayout.addWidget(self.button_show_plot_oxygen, 6, 3, 1, 1)
        self.button_show_plot_drugs = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_show_plot_drugs.sizePolicy().hasHeightForWidth())
        self.button_show_plot_drugs.setSizePolicy(sizePolicy)
        self.button_show_plot_drugs.setMinimumSize(QtCore.QSize(120, 32))
        self.button_show_plot_drugs.setMaximumSize(QtCore.QSize(200, 32))
        self.button_show_plot_drugs.setObjectName("button_show_plot_drugs")
        self.gridLayout.addWidget(self.button_show_plot_drugs, 7, 3, 1, 1)
        self.button_show_plot_blood = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_show_plot_blood.sizePolicy().hasHeightForWidth())
        self.button_show_plot_blood.setSizePolicy(sizePolicy)
        self.button_show_plot_blood.setMinimumSize(QtCore.QSize(120, 32))
        self.button_show_plot_blood.setMaximumSize(QtCore.QSize(200, 32))
        self.button_show_plot_blood.setObjectName("button_show_plot_blood")
        self.gridLayout.addWidget(self.button_show_plot_blood, 8, 3, 1, 1)
        self.button_show_plot_stretchers = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_show_plot_stretchers.sizePolicy().hasHeightForWidth())
        self.button_show_plot_stretchers.setSizePolicy(sizePolicy)
        self.button_show_plot_stretchers.setMinimumSize(QtCore.QSize(120, 32))
        self.button_show_plot_stretchers.setMaximumSize(QtCore.QSize(200, 32))
        self.button_show_plot_stretchers.setObjectName("button_show_plot_stretchers")
        self.gridLayout.addWidget(self.button_show_plot_stretchers, 9, 3, 1, 1)
        self.button_show_plot_beds = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_show_plot_beds.sizePolicy().hasHeightForWidth())
        self.button_show_plot_beds.setSizePolicy(sizePolicy)
        self.button_show_plot_beds.setMinimumSize(QtCore.QSize(120, 32))
        self.button_show_plot_beds.setMaximumSize(QtCore.QSize(200, 32))
        self.button_show_plot_beds.setObjectName("button_show_plot_beds")
        self.gridLayout.addWidget(self.button_show_plot_beds, 10, 3, 1, 1)
        self.button_show_plot_MCI_kits = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_show_plot_MCI_kits.sizePolicy().hasHeightForWidth())
        self.button_show_plot_MCI_kits.setSizePolicy(sizePolicy)
        self.button_show_plot_MCI_kits.setMinimumSize(QtCore.QSize(120, 32))
        self.button_show_plot_MCI_kits.setMaximumSize(QtCore.QSize(200, 32))
        self.button_show_plot_MCI_kits.setObjectName("button_show_plot_MCI_kits")
        self.gridLayout.addWidget(self.button_show_plot_MCI_kits, 11, 3, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.button_generate_report = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_generate_report.sizePolicy().hasHeightForWidth())
        self.button_generate_report.setSizePolicy(sizePolicy)
        self.button_generate_report.setMaximumSize(QtCore.QSize(200, 16777215))
        self.button_generate_report.setObjectName("button_generate_report")
        self.verticalLayout_9.addWidget(self.button_generate_report)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Add items to department dropdown
        departments = DEPARTMENTS
        self.comboBox_department.addItems(departments)
        self.comboBox_department.setCurrentIndex(0)

        bed_departments = ['Emergency Department', 'Operating Theater', 'High Dependency Unit', 'Medical/Surgical Department', 'Rest Of Hospital']
        self.comboBox_department_Beds.addItems(bed_departments)
        self.comboBox_department_Beds.setCurrentIndex(0)

        MCI_kit_types = ['Walking | Emergency Department', 'Non-Walking | Emergency Department', 'Non-Walking | Operating Theater', 'Non-Walking | High Dependency Unit', 'Non-Walking | Medical/Surgical Department']
        self.comboBox_department_MCI_Kits.addItems(MCI_kit_types)
        self.comboBox_department_MCI_Kits.setCurrentIndex(0)

        # Add functionality to buttons
        self.button_select_file.clicked.connect(self.selectFile)
        self.button_run.clicked.connect(self.run_assessment)
        self.app = app
        self.progressBar.setRange(0, 100)
        self.progressBar.setProperty("value", 0)
        self.button_show_plot_nurses.clicked.connect(lambda: self.show_plot('Nurse'))
        self.button_show_plot_fuel.clicked.connect(lambda: self.show_plot('Fuel'))
        self.button_show_plot_water.clicked.connect(lambda: self.show_plot('Water'))
        self.button_show_plot_oxygen.clicked.connect(lambda: self.show_plot('Oxygen'))
        self.button_show_plot_drugs.clicked.connect(lambda: self.show_plot('MedicalDrugs'))
        self.button_show_plot_blood.clicked.connect(lambda: self.show_plot('Blood')) 
        self.button_show_plot_stretchers.clicked.connect(lambda: self.show_plot('Stretcher'))  
        self.button_show_plot_MCI_kits.clicked.connect(lambda: self.show_plot(self.format_MCI_kit_resource_name()))
        self.button_show_plot_beds.clicked.connect(lambda: self.show_plot(self.format_bed_resource_name()))
        self.button_generate_report.clicked.connect(lambda: ReportGenerator.generate_report(self.system, self.input_file_location))

        # Disable pre-defined MCI inputs if user-defined MCI is selected
        self.radioButton_userDefinedMCI.toggled.connect(self.disableMCIScenarioInputForCustomScenario)

        # Update pre-defined MCI scenario dropdown
        self.update_MCI_stress_scenario_dropdown()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MCI Planning Tool"))
        self.button_select_file.setText(_translate("MainWindow", "Select Input File"))
        self.label_input_file_location.setText(_translate("MainWindow", "Input file location                                                                                                                   "))
        self.label_MassCasualtyIncidentScenario.setText(_translate("MainWindow", "Mass Casualty Incident (MCI) Scenario"))
        self.radioButton_userDefinedMCI.setText(_translate("MainWindow", "Use user-defined MCI Scenario"))
        self.radioButton_preDefinedMCI.setText(_translate("MainWindow", "Use pre-defined MCI Scenario"))
        self.label_preDefinedMCIType.setText(_translate("MainWindow", "MCI Type"))
        self.label_NumberOfPatients.setText(_translate("MainWindow", "Number of Patients"))
        self.textEdit_NumberOfPatients.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_InvestigatedPeriod.setText(_translate("MainWindow", "Investigated Period [days]"))
        self.textEdit_InvestigatedPeriod.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.button_run.setText(_translate("MainWindow", "Run"))
        self.label_measures_of_service.setText(_translate("MainWindow", "Measures of Service"))
        self.label_choose_department.setText(_translate("MainWindow", "Choose department:"))
        self.label_choose_patient_type.setText(_translate("MainWindow", "Choose patient type:"))
        self.label_mortality_rate_before_24h_output.setText(_translate("MainWindow", "0.0"))
        self.label_mortality_rate_after_24.setText(_translate("MainWindow", "Mortality Rate After 24h:"))
        self.label_average_length_of_stay.setText(_translate("MainWindow", "Average Length Of Stay:"))
        self.label_surgeries_performed_output.setText(_translate("MainWindow", "0.0"))
        self.label_mortality_rate_before_24h.setText(_translate("MainWindow", "Mortality Rate In the First 24h:"))
        self.label_average_length_of_stay_output.setText(_translate("MainWindow", "0.0"))
        self.label_mortality_rate_after_24h_output.setText(_translate("MainWindow", "0.0"))
        self.label_surgeries_cancelled_output.setText(_translate("MainWindow", "0.0"))
        self.label_surgeries_performed.setText(_translate("MainWindow", "Surgeries Performed:"))
        self.label_surgeries_cancelled.setText(_translate("MainWindow", "Surgeries Cancelled:"))
        self.label_medical_drugs.setText(_translate("MainWindow", "Medical Drugs"))
        self.label_fuel.setText(_translate("MainWindow", "Fuel"))
        self.label_beds.setText(_translate("MainWindow", "Beds"))
        self.label_water.setText(_translate("MainWindow", "Water"))
        self.label_department_nurses.setText(_translate("MainWindow", "Entire Hospital"))
        self.label_stretchers.setText(_translate("MainWindow", "Stretchers"))
        self.label_blood.setText(_translate("MainWindow", "Blood"))
        self.label_resources.setText(_translate("MainWindow", "Resources"))
        self.label_oxygen.setText(_translate("MainWindow", "Oxygen"))
        self.label_department_drugs.setText(_translate("MainWindow", "Entire Hospital"))
        self.label_MCI_kits.setText(_translate("MainWindow", "MCI Kits"))
        self.label_nurses.setText(_translate("MainWindow", "Nurses"))
        self.label_department_fuel.setText(_translate("MainWindow", "Entire Hospital"))
        self.label_department_oxygen.setText(_translate("MainWindow", "Entire Hospital"))
        self.label_department_blood.setText(_translate("MainWindow", "Entire Hospital"))
        self.label_department_water.setText(_translate("MainWindow", "Entire Hospital"))
        self.label_department_stretchers.setText(_translate("MainWindow", "Entire Hospital"))
        self.label_department.setText(_translate("MainWindow", "Department"))
        self.button_show_plot_nurses.setText(_translate("MainWindow", "Show Plot"))
        self.button_show_plot_fuel.setText(_translate("MainWindow", "Show Plot"))
        self.button_show_plot_water.setText(_translate("MainWindow", "Show Plot"))
        self.button_show_plot_oxygen.setText(_translate("MainWindow", "Show Plot"))
        self.button_show_plot_drugs.setText(_translate("MainWindow", "Show Plot"))
        self.button_show_plot_blood.setText(_translate("MainWindow", "Show Plot"))
        self.button_show_plot_stretchers.setText(_translate("MainWindow", "Show Plot"))
        self.button_show_plot_beds.setText(_translate("MainWindow", "Show Plot"))
        self.button_show_plot_MCI_kits.setText(_translate("MainWindow", "Show Plot"))
        self.button_generate_report.setText(_translate("MainWindow", "Generate Report"))

# Second Window Class for Plotting
class SecondWindow(QMainWindow):

    def __init__(self, system, resource_name, comboBox_departments, comboBox_patient_type):
        super(SecondWindow, self).__init__()
        self.main_widget = QtWidgets.QWidget()
        self.setCentralWidget(self.main_widget)

        layout = QtWidgets.QVBoxLayout(self.main_widget)
        sc = MyMplCanvas(system, resource_name, comboBox_departments, comboBox_patient_type, parent=self.main_widget, width = 300, height = 300)
        layout.addWidget(sc)
        self.show()

class MyMplCanvas(FigureCanvas):

    def __init__(self, system, resource_name, comboBox_departments, comboBox_patient_type, parent=None, width= 300, height= 300):
        self.plot(system, resource_name)
        fig = self.axes.get_figure()
        super(MyMplCanvas, self).__init__(fig)  

        FigureCanvas.__init__(self, fig)
        self.setParent(parent)

        FigureCanvas.setSizePolicy(self, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        FigureCanvas.updateGeometry(self)
        self.draw()

    def plot(self, system, resource_name, department='All', patient_type='All'):
        plotter_object = Plotter.Plotter()
        x_axis_label = 'Time step [hour]'
        y_axis_label = f'{resource_name} {RESOURCE_UNITS[resource_name]}'
        self.axes = plotter_object.setup_lor_plot_fig(x_axis_label, y_axis_label)
        resilience_calculator = get_resilience_calculator(system, department, patient_type, resilience_calculator_class=ResilienceCalculator.ReCoDeSResilienceCalculator)
        plotter_object.plot_single_resource(list(range(system.START_TIME_STEP, system.time_step+1)), resilience_calculator.system_supply[resource_name], 
                                                resilience_calculator.system_demand[resource_name], 
                                                resilience_calculator.system_consumption[resource_name], self.axes) 
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    # Added app as input to add .processEvents and update progress bar
    ui.setupUi(MainWindow, app)
    MainWindow.show()
    sys.exit(app.exec())
